import "../widgets/dragbox.js";
import "../widgets/ui_widgets2.js";
import "../widgets/ui_panel.js";
import "../widgets/ui_treeview.js";
import { ToolStack } from "../path-controller/controller.js";
import "../util/ScreenOverdraw.js";
import "../widgets/ui_curvewidget.js";
import { Vector2 } from "../path-controller/util/vectormath.js";
import { ScreenArea, Area, ScreenAreaAny, AreaAny } from "./ScreenArea.js";
import * as ui_menu from "../widgets/ui_menu.js";
import "../path-controller/util/struct.js";
import { KeyMap } from "../path-controller/util/simple_events.js";
import { ScreenBorder, ScreenVert, ScreenHalfEdge } from "./FrameManager_mesh.js";
export { ScreenBorder, ScreenVert, ScreenHalfEdge } from "./FrameManager_mesh.js";
import { UIBase, IUIBaseConstructor } from "../core/ui_base";
import * as FrameManager_mesh from "./FrameManager_mesh.js";
import "../widgets/ui_widgets.js";
import "../widgets/ui_tabs.js";
import "../widgets/ui_colorpicker2.js";
import "../widgets/ui_noteframe.js";
import "../widgets/ui_listbox.js";
import "../widgets/ui_table.js";
import { IsScreenTag } from "./constants.js";
import { IContextBase } from "../core/context_base.js";
import { StructReader } from "../util/nstructjs.js";
import "./AreaDocker";
export declare function registerToolStackGetter(func: () => ToolStack): void;
export declare function purgeUpdateStack(): void;
/**
 * Base class for app workspaces
 *
 attributes:

 inherit-scale : don't resize to fit whole screen, use cssbox scaling

 */
export declare class Screen<CTX extends IContextBase = IContextBase> extends UIBase<CTX> {
    static STRUCT: string;
    [IsScreenTag]: boolean;
    snapLimit: number;
    fullScreen: boolean;
    globalCSS: HTMLStyleElement;
    _do_updateSize: boolean;
    _resize_callbacks: ((size: Vector2) => void)[];
    allBordersMovable: boolean;
    needsBorderRegen: boolean;
    _popup_safe: number;
    testAllKeyMaps: boolean;
    needsTabRecalc: boolean;
    _screen_id: number;
    _popups: UIBase[];
    keymap: KeyMap;
    size: Vector2;
    pos: Vector2;
    oldpos: Vector2;
    idgen: number;
    sareas: ScreenAreaAny[] & {
        active?: ScreenAreaAny;
    };
    mpos: [number, number];
    screenborders: ScreenBorder[];
    screenverts: ScreenVert[];
    _vertmap: Record<string, ScreenVert>;
    _edgemap: Record<string, ScreenBorder>;
    _idmap: Record<string, ScreenVert | ScreenBorder>;
    _aabb: [Vector2, Vector2];
    listen_timer?: any;
    _last_ckey1?: string;
    _update_gen?: Generator<void>;
    _last_scrollstyle_key?: string;
    _debug_overlay?: HTMLElement;
    uidata?: string;
    constructor();
    get borders(): Generator<ScreenBorder<IContextBase<any, import("../pathux.js").IToolStack>>, void, unknown>;
    get listening(): boolean;
    get ctx(): CTX;
    set ctx(val: CTX);
    static fromJSON(obj: Record<string, unknown>, schedule_resize?: boolean): void;
    static define(): {
        tagname: string;
    };
    static newSTRUCT(): HTMLElement;
    setPosSize(x: number, y: number, w: number, h: number): void;
    setSize(w: number, h: number): void;
    setPos(x: number, y: number): void;
    init(): void;
    /**
     *
     * @param {*} style May be a string, a CSSStyleSheet instance, or a style tag
     * @returns Promise fulfilled when style has been merged
     */
    mergeGlobalCSS(style: string | CSSStyleSheet | HTMLStyleElement): Promise<void>;
    newScreenArea(): ScreenArea<IContextBase<any, import("../pathux.js").IToolStack>>;
    copy(): this;
    findScreenArea(x: number, y: number): ScreenAreaAny | undefined;
    pickElement<T extends UIBase = UIBase>(x: number, y: number, args?: Parameters<UIBase["pickElement"]>[2], marginy?: number, nodeclass?: IUIBaseConstructor<UIBase>, excluded_classes?: IUIBaseConstructor[]): T | undefined;
    _enterPopupSafe(): void;
    _allAreas(): Generator<(number | Area<any> | ScreenAreaAny)[], void, unknown>;
    _exitPopupSafe(): void;
    popupMenu(menu: ui_menu.Menu, x: number, y: number): ui_menu.Menu<IContextBase<any, import("../pathux.js").IToolStack>>;
    /**
     *
     * @param popupDelay : if non-zero, wait for popup to layout for popupDelay miliseconds,
     *                     then move the popup so it's fully inside the window (if it's outsize).
     *
     * */
    popup(owning_node: UIBase, elem_or_x: UIBase | number, y: number, closeOnMouseOut?: boolean, popupDelay?: number): UIBase<IContextBase<any, import("../pathux.js").IToolStack>, unknown> & {
        background: string;
        end: () => void;
    };
    draggablePopup(x: number, y: number): UIBase<IContextBase<any, import("../pathux.js").IToolStack>, unknown>;
    /** makes a popup at x,y and returns a new container-x for it */
    _popup(owning_node: UIBase, elem_or_x: UIBase | number, y: number, closeOnMouseOut?: boolean): UIBase<IContextBase<any, import("../pathux.js").IToolStack>, unknown> & {
        background: string;
        end: () => void;
    };
    _recalcAABB(save?: boolean): {
        [k: number]: number | undefined;
        0: number;
        1: number;
        length: number;
        LEN: 2;
        [Symbol.iterator]: (() => ArrayIterator<any>) | (() => ArrayIterator<number>);
        slice: (start?: number, end?: number) => number[];
        load(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        load2(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        normalizedDot(b: import("../pathux.js").IBaseVector<2>): number;
        equals(b: import("../pathux.js").IBaseVector<2>): boolean;
        zero(): /*elided*/ any;
        negate(): /*elided*/ any;
        combine(b: import("../pathux.js").IBaseVector<2>, u: number, v: number): /*elided*/ any;
        interp(b: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
        add(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        addFac(b: import("../pathux.js").IBaseVector<2>, f: number): /*elided*/ any;
        fract(): /*elided*/ any;
        sub(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        mul(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        div(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        mulScalar(b: number): /*elided*/ any;
        divScalar(b: number): /*elided*/ any;
        addScalar(b: number): /*elided*/ any;
        subScalar(b: number): /*elided*/ any;
        minScalar(b: number): /*elided*/ any;
        maxScalar(b: number): /*elided*/ any;
        ceil(): /*elided*/ any;
        floor(): /*elided*/ any;
        abs(): /*elided*/ any;
        min(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        max(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        clamp(min: number, max: number): /*elided*/ any;
        vectorDotDistance(b: import("../pathux.js").IBaseVector<2>): number;
        vectorDistance(b: import("../pathux.js").IBaseVector<2>): number;
        vectorDistanceSqr(b: import("../pathux.js").IBaseVector<2>): number;
        copy(): /*elided*/ any;
        vectorLengthSqr(): number;
        vectorLength(): number;
        rot2d(A: number, axis?: number): /*elided*/ any;
        dot(b: import("../pathux.js").IBaseVector<2>): number;
        loadX(x: number): /*elided*/ any;
        loadXY(x: number, y: number): /*elided*/ any;
        swapAxes(axis1: 0 | 1, axis2: 0 | 1): /*elided*/ any;
        sinterp(v2: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
        perpSwap(axis1?: 0 | 1, axis2?: 0 | 1, sign?: number): /*elided*/ any;
        normalize(): /*elided*/ any;
        multVecMatrix(matrix: import("../pathux.js").Matrix4, ignore_w?: boolean): /*elided*/ any;
        mulVecQuat(q: import("../pathux.js").IQuat): /*elided*/ any;
        preNormalizedAngle(v2: import("../pathux.js").IBaseVector<2>): number;
        loadSTRUCT(reader: StructReader</*elided*/ any>): void;
    }[];
    load(): void;
    save(): void;
    popupArea(area_class: typeof Area): any;
    remove(trigger_destroy?: boolean): void;
    unlisten(): void;
    checkCSSSize(): void;
    getBoolAttribute(attr: string, defaultval?: boolean): boolean;
    updateSize(): void;
    listen(args?: {
        updateSize: boolean;
    }): void;
    _calcSizeKey(w: number, h: number, x: number, y: number, dpi: number, scale: number): string;
    _ondestroy(): void;
    destroy(): void;
    clear(): void;
    _test_save(): void;
    loadJSON(obj: Record<string, any>, schedule_resize?: boolean): void;
    toJSON(): {
        sareas: ScreenAreaAny[] & {
            active?: ScreenAreaAny;
        };
        size: {
            [k: number]: number | undefined;
            0: number;
            1: number;
            length: number;
            LEN: 2;
            [Symbol.iterator]: (() => ArrayIterator<any>) | (() => ArrayIterator<number>);
            slice: (start?: number, end?: number) => number[];
            load(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
            load2(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
            normalizedDot(b: import("../pathux.js").IBaseVector<2>): number;
            equals(b: import("../pathux.js").IBaseVector<2>): boolean;
            zero(): /*elided*/ any;
            negate(): /*elided*/ any;
            combine(b: import("../pathux.js").IBaseVector<2>, u: number, v: number): /*elided*/ any;
            interp(b: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
            add(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
            addFac(b: import("../pathux.js").IBaseVector<2>, f: number): /*elided*/ any;
            fract(): /*elided*/ any;
            sub(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
            mul(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
            div(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
            mulScalar(b: number): /*elided*/ any;
            divScalar(b: number): /*elided*/ any;
            addScalar(b: number): /*elided*/ any;
            subScalar(b: number): /*elided*/ any;
            minScalar(b: number): /*elided*/ any;
            maxScalar(b: number): /*elided*/ any;
            ceil(): /*elided*/ any;
            floor(): /*elided*/ any;
            abs(): /*elided*/ any;
            min(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
            max(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
            clamp(min: number, max: number): /*elided*/ any;
            vectorDotDistance(b: import("../pathux.js").IBaseVector<2>): number;
            vectorDistance(b: import("../pathux.js").IBaseVector<2>): number;
            vectorDistanceSqr(b: import("../pathux.js").IBaseVector<2>): number;
            copy(): /*elided*/ any;
            vectorLengthSqr(): number;
            vectorLength(): number;
            rot2d(A: number, axis?: number): /*elided*/ any;
            dot(b: import("../pathux.js").IBaseVector<2>): number;
            loadX(x: number): /*elided*/ any;
            loadXY(x: number, y: number): /*elided*/ any;
            swapAxes(axis1: 0 | 1, axis2: 0 | 1): /*elided*/ any;
            sinterp(v2: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
            perpSwap(axis1?: 0 | 1, axis2?: 0 | 1, sign?: number): /*elided*/ any;
            normalize(): /*elided*/ any;
            multVecMatrix(matrix: import("../pathux.js").Matrix4, ignore_w?: boolean): /*elided*/ any;
            mulVecQuat(q: import("../pathux.js").IQuat): /*elided*/ any;
            preNormalizedAngle(v2: import("../pathux.js").IBaseVector<2>): number;
            loadSTRUCT(reader: StructReader</*elided*/ any>): void;
        };
        idgen: number;
    };
    getHotKey(toolpath: string): import("../pathux.js").HotKey | undefined;
    addEventListener(type: string, cb: any, options?: boolean | AddEventListenerOptions): void;
    removeEventListener(type: string, cb: any, options?: boolean | EventListenerOptions): void;
    execKeyMap(e: KeyboardEvent): boolean | undefined;
    calcTabOrder(): void;
    drawUpdate(): void;
    update(): void;
    purgeUpdateStack(): void;
    completeSetCSS(): void;
    completeUpdate(): void;
    updateScrollStyling(): void;
    update_intern(): Generator<undefined, void, unknown>;
    loadFromVerts(): void;
    /** merges sarea into the screen area opposite to sarea*/
    collapseArea(sarea: ScreenAreaAny, border?: ScreenBorder): this | undefined;
    splitArea(sarea: ScreenAreaAny, t?: number, horiz?: boolean): ScreenArea<any>;
    setCSS(): void;
    regenScreenMesh(snapLimit?: number): void;
    regenBorders_stage2(): void;
    hasBorder(b: ScreenBorder): boolean;
    killScreenVertex(v: ScreenVert): this;
    freeBorder(b: FrameManager_mesh.ScreenBorderAny, sarea?: ScreenAreaAny): void;
    killBorder(b: ScreenBorder): this | undefined;
    regenBorders(): void;
    _get_debug_overlay(): HTMLElement;
    updateDebugBoxes(): void;
    checkAreaConstraint(sarea: ScreenAreaAny, checkOnly?: boolean): number | false;
    walkBorderLine(b: ScreenBorder): ScreenBorder<IContextBase<any, import("../pathux.js").IToolStack>>[];
    moveBorderWithoutVerts(halfedge: ScreenHalfEdge, df: number): void;
    moveBorder(b: ScreenBorder, df: number, strict?: boolean): boolean;
    moveBorderSimple(b: ScreenBorder, df: number, strict?: boolean): boolean;
    moveBorderUnused(b: ScreenBorder, df: number, strict?: boolean): boolean;
    solveAreaConstraints(snapArgument?: boolean): void;
    snapScreenVerts(fitToSize?: boolean): void;
    on_resize(oldsize: Vector2 | number[], newsize?: Vector2 | number[], _set_key?: boolean): void;
    _fireResizeCB(oldsize?: {
        [k: number]: number | undefined;
        0: number;
        1: number;
        length: number;
        LEN: 2;
        [Symbol.iterator]: (() => ArrayIterator<any>) | (() => ArrayIterator<number>);
        slice: (start?: number, end?: number) => number[];
        load(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        load2(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        normalizedDot(b: import("../pathux.js").IBaseVector<2>): number;
        equals(b: import("../pathux.js").IBaseVector<2>): boolean;
        zero(): /*elided*/ any;
        negate(): /*elided*/ any;
        combine(b: import("../pathux.js").IBaseVector<2>, u: number, v: number): /*elided*/ any;
        interp(b: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
        add(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        addFac(b: import("../pathux.js").IBaseVector<2>, f: number): /*elided*/ any;
        fract(): /*elided*/ any;
        sub(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        mul(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        div(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        mulScalar(b: number): /*elided*/ any;
        divScalar(b: number): /*elided*/ any;
        addScalar(b: number): /*elided*/ any;
        subScalar(b: number): /*elided*/ any;
        minScalar(b: number): /*elided*/ any;
        maxScalar(b: number): /*elided*/ any;
        ceil(): /*elided*/ any;
        floor(): /*elided*/ any;
        abs(): /*elided*/ any;
        min(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        max(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        clamp(min: number, max: number): /*elided*/ any;
        vectorDotDistance(b: import("../pathux.js").IBaseVector<2>): number;
        vectorDistance(b: import("../pathux.js").IBaseVector<2>): number;
        vectorDistanceSqr(b: import("../pathux.js").IBaseVector<2>): number;
        copy(): /*elided*/ any;
        vectorLengthSqr(): number;
        vectorLength(): number;
        rot2d(A: number, axis?: number): /*elided*/ any;
        dot(b: import("../pathux.js").IBaseVector<2>): number;
        loadX(x: number): /*elided*/ any;
        loadXY(x: number, y: number): /*elided*/ any;
        swapAxes(axis1: 0 | 1, axis2: 0 | 1): /*elided*/ any;
        sinterp(v2: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
        perpSwap(axis1?: 0 | 1, axis2?: 0 | 1, sign?: number): /*elided*/ any;
        normalize(): /*elided*/ any;
        multVecMatrix(matrix: import("../pathux.js").Matrix4, ignore_w?: boolean): /*elided*/ any;
        mulVecQuat(q: import("../pathux.js").IQuat): /*elided*/ any;
        preNormalizedAngle(v2: import("../pathux.js").IBaseVector<2>): number;
        loadSTRUCT(reader: StructReader</*elided*/ any>): void;
    }): void;
    getScreenVert(pos: Vector2 | number[], added_id?: string, floating?: boolean): ScreenVert<IContextBase<any, import("../pathux.js").IToolStack>>;
    isBorderOuter(border: ScreenBorder): boolean;
    isBorderMovable(b: ScreenBorder, limit?: number): boolean;
    getScreenBorder(sarea: ScreenAreaAny, co1: Vector2 | ScreenVert<any>, co2: Vector2 | ScreenVert<any>, side: number): ScreenBorder;
    minmaxArea(sarea: ScreenAreaAny, mm?: any): any;
    areasBorder(sarea1: ScreenAreaAny, sarea2: ScreenAreaAny): boolean;
    replaceArea(dst: ScreenAreaAny, src: ScreenAreaAny): void;
    _internalRegenAll(): void;
    _updateAll(): void;
    removeArea(sarea: ScreenAreaAny): void;
    appendChild<T extends Node>(child: T): T;
    add(child: Node): Node;
    hintPickerTool(): void;
    removeAreaTool(border?: ScreenBorder): void;
    moveAttachTool(sarea: ScreenArea, mpos?: [number, number] | number[] | Vector2, elem?: any, pointerId?: number): void;
    splitTool(): void;
    areaDragTool(sarea?: ScreenAreaAny | undefined): void;
    makeBorders(): void;
    cleanupBorders(): void;
    mergeBlankAreas(): void;
    floatArea(area: AreaAny): ScreenArea<IContextBase<any, import("../pathux.js").IToolStack>>;
    on_keydown(e: KeyboardEvent): void;
    on_keyup(e: KeyboardEvent): void | boolean;
    on_keypress(e: KeyboardEvent): void | boolean;
    draw(): void;
    afterSTRUCT(): void;
    loadSTRUCT(reader: StructReader<this>): this;
    saveUIData(): string | undefined;
    loadUIData(str: string | undefined): void;
}
export declare function startEvents<CTX extends IContextBase>(getScreenFunc: () => Screen): void;
export declare function stopEvents(): () => Screen;
export declare function setKeyboardDom(dom: Window): void;
/** Sets options passed to addEventListener() for on_keydown hotkey handler */
export declare function setKeyboardOpts(opts: AddEventListenerOptions): void;
export declare function _onEventsStart(cb: () => void): void;
export declare function _onEventsStop(cb: () => void): void;
//# sourceMappingURL=FrameManager.d.ts.map