import type { Screen } from "./FrameManager";
import { UIBase } from "../core/ui_base";
import { Container } from "../core/ui.js";
import { EnumProperty } from "../path-controller/toolsys/toolprop.js";
import { ScreenBorder } from "./FrameManager_mesh.js";
import { contextWrangler } from "./area_wrangler.js";
import { IContextBase } from "../core/context_base.js";
import { Vector2 } from "../pathux.js";
import { StructReader } from "../util/nstructjs";
import type { KeyMap } from "../path-controller/util/simple_events.js";
import type { AreaDocker } from "./AreaDocker";
import type { DropBox } from "../widgets/ui_menu";
import { AreaConstructorParam, AreaFlags } from "./area_base";
export interface IAreaDef {
    tagname: string;
    /** used by buildEditorsAPI, if it doesn't exit areaname will be used */
    apiname?: string;
    areaname: string;
    flag?: number;
    uiname?: string;
    icon?: number;
    borderLock?: number;
}
export { AreaFlags };
export * from "./area_wrangler.js";
export { contextWrangler };
export declare const BorderMask: {
    LEFT: number;
    BOTTOM: number;
    RIGHT: number;
    TOP: number;
    ALL: number;
};
export declare const BorderSides: {
    LEFT: number;
    BOTTOM: number;
    RIGHT: number;
    TOP: number;
};
/**
 * Base class for all editors
 **/
export declare class Area<CTX extends IContextBase = IContextBase> extends UIBase<CTX> {
    [Symbol.IsAreaTag]: boolean;
    static STRUCT: string;
    borderLock: number;
    flag: number;
    pos?: Vector2;
    size?: Vector2;
    inactive: boolean;
    areaDragToolEnabled: boolean;
    owning_sarea: ScreenArea<CTX> | undefined;
    _area_id: number;
    minSize: number[];
    maxSize: (number | undefined)[];
    keymap?: KeyMap<CTX>;
    header: Container<CTX> | undefined;
    switcher?: AreaDocker<CTX> | DropBox<CTX> | undefined;
    helppicker: (UIBase<CTX> & {
        iconsheet?: number;
    }) | undefined;
    saved_uidata: string | undefined;
    areaName: string | undefined;
    dead: boolean;
    constructor();
    get floating(): number;
    set floating(val: number);
    /**
     * Get active area as defined by push_ctx_active and pop_ctx_active.
     *
     * Type should be an Area subclass, if undefined the last accessed area
     * will be returned.
     * */
    static getActiveArea(type?: AreaConstructorParam): Area<IContextBase<any, import("../pathux.js").IToolStack>> | undefined;
    static unregister(cls: AreaConstructorParam): void;
    static register(_cls: any, isInternal?: boolean): void;
    static makeAreasEnum(): EnumProperty<string>;
    static getAreaName<CTX extends IContextBase = IContextBase>(area: Area<CTX>): string;
    static define(): IAreaDef;
    static newSTRUCT(): HTMLElement;
    init(): void;
    _get_v_suffix(): string;
    /**
     * Return a list of keymaps used by this editor
     */
    getKeyMaps(): KeyMap<CTX>[];
    on_fileload(isActiveEditor: boolean): void;
    buildDataPath(): string;
    saveData(): {
        _area_id: number;
        areaName: string | undefined;
    };
    loadData(obj: Record<string, unknown>): this;
    draw(): void;
    copy(): HTMLElement;
    on_resize(size: number[] | Vector2): void;
    on_area_focus(): void;
    on_area_blur(): void;
    /** called when editors are swapped with another editor type*/
    on_area_active(): void;
    /** called when editors are swapped with another editor type*/
    on_area_inactive(): void;
    push_ctx_active(dontSetLastRef?: boolean): void;
    /**
     * see push_ctx_active
     * */
    pop_ctx_active(dontSetLastRef?: boolean): void;
    getScreen(): UIBase<CTX> | undefined;
    toJSON(): Record<string, unknown> & {
        areaname: string;
        _area_id: number;
    };
    loadJSON(obj: Record<string, unknown>): this;
    getBarHeight(): number;
    makeAreaSwitcher(container: Container<CTX>): AreaDocker<CTX> | DropBox<CTX>;
    makeHeader(container: Container<CTX>, add_note_area?: boolean, make_draggable?: boolean): Container<CTX>;
    setCSS(): void;
    update(): void;
    loadSTRUCT(reader: StructReader<this>): void;
    _isDead(): true | undefined;
    afterSTRUCT(): void;
    _getSavedUIData(): string;
}
export declare class ScreenArea<CTX extends IContextBase = IContextBase> extends UIBase<CTX> {
    static STRUCT: string;
    keymap?: KeyMap;
    screen?: Screen<CTX>;
    _flag: number;
    _borders: ScreenBorder<CTX>[];
    _verts: import("./FrameManager_mesh.js").ScreenVert<CTX>[];
    dead: boolean;
    _sarea_id: number;
    _pos: Vector2;
    _size: Vector2;
    area: Area<CTX> | undefined;
    editors: Area<CTX>[] & {
        remove(item: Area<CTX>, b?: boolean): void;
    };
    editormap: Record<string, Area<CTX>>;
    switcherData?: any;
    on_keyup?: (e: KeyboardEvent) => void | boolean;
    on_keypress?: (e: KeyboardEvent) => void | boolean;
    constructor();
    get floating(): boolean;
    set floating(val: boolean);
    get flag(): number;
    set flag(v: number);
    get borderLock(): number;
    get minSize(): number[] | {
        [k: number]: number | undefined;
        0: number;
        1: number;
        length: number;
        LEN: 2;
        [Symbol.iterator]: (() => ArrayIterator<any>) | (() => ArrayIterator<number>);
        slice: (start?: number, end?: number) => number[];
        load(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        load2(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        normalizedDot(b: import("../pathux.js").IBaseVector<2>): number;
        equals(b: import("../pathux.js").IBaseVector<2>): boolean;
        zero(): /*elided*/ any;
        negate(): /*elided*/ any;
        combine(b: import("../pathux.js").IBaseVector<2>, u: number, v: number): /*elided*/ any;
        interp(b: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
        add(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        addFac(b: import("../pathux.js").IBaseVector<2>, f: number): /*elided*/ any;
        fract(): /*elided*/ any;
        sub(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        mul(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        div(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        mulScalar(b: number): /*elided*/ any;
        divScalar(b: number): /*elided*/ any;
        addScalar(b: number): /*elided*/ any;
        subScalar(b: number): /*elided*/ any;
        minScalar(b: number): /*elided*/ any;
        maxScalar(b: number): /*elided*/ any;
        ceil(): /*elided*/ any;
        floor(): /*elided*/ any;
        abs(): /*elided*/ any;
        min(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        max(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        clamp(min: number, max: number): /*elided*/ any;
        vectorDotDistance(b: import("../pathux.js").IBaseVector<2>): number;
        vectorDistance(b: import("../pathux.js").IBaseVector<2>): number;
        vectorDistanceSqr(b: import("../pathux.js").IBaseVector<2>): number;
        copy(): /*elided*/ any;
        vectorLengthSqr(): number;
        vectorLength(): number;
        rot2d(A: number, axis?: number): /*elided*/ any;
        dot(b: import("../pathux.js").IBaseVector<2>): number;
        loadX(x: number): /*elided*/ any;
        loadXY(x: number, y: number): /*elided*/ any;
        swapAxes(axis1: 0 | 1, axis2: 0 | 1): /*elided*/ any;
        sinterp(v2: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
        perpSwap(axis1?: 0 | 1, axis2?: 0 | 1, sign?: number): /*elided*/ any;
        normalize(): /*elided*/ any;
        multVecMatrix(matrix: import("../pathux.js").Matrix4, ignore_w?: boolean): /*elided*/ any;
        mulVecQuat(q: import("../pathux.js").IQuat): /*elided*/ any;
        preNormalizedAngle(v2: import("../pathux.js").IBaseVector<2>): number;
        loadSTRUCT(reader: StructReader</*elided*/ any>): void;
    };
    get maxSize(): (number | undefined)[] | {
        [k: number]: number | undefined;
        0: number;
        1: number;
        length: number;
        LEN: 2;
        [Symbol.iterator]: (() => ArrayIterator<any>) | (() => ArrayIterator<number>);
        slice: (start?: number, end?: number) => number[];
        load(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        load2(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        normalizedDot(b: import("../pathux.js").IBaseVector<2>): number;
        equals(b: import("../pathux.js").IBaseVector<2>): boolean;
        zero(): /*elided*/ any;
        negate(): /*elided*/ any;
        combine(b: import("../pathux.js").IBaseVector<2>, u: number, v: number): /*elided*/ any;
        interp(b: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
        add(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        addFac(b: import("../pathux.js").IBaseVector<2>, f: number): /*elided*/ any;
        fract(): /*elided*/ any;
        sub(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        mul(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        div(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        mulScalar(b: number): /*elided*/ any;
        divScalar(b: number): /*elided*/ any;
        addScalar(b: number): /*elided*/ any;
        subScalar(b: number): /*elided*/ any;
        minScalar(b: number): /*elided*/ any;
        maxScalar(b: number): /*elided*/ any;
        ceil(): /*elided*/ any;
        floor(): /*elided*/ any;
        abs(): /*elided*/ any;
        min(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        max(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        clamp(min: number, max: number): /*elided*/ any;
        vectorDotDistance(b: import("../pathux.js").IBaseVector<2>): number;
        vectorDistance(b: import("../pathux.js").IBaseVector<2>): number;
        vectorDistanceSqr(b: import("../pathux.js").IBaseVector<2>): number;
        copy(): /*elided*/ any;
        vectorLengthSqr(): number;
        vectorLength(): number;
        rot2d(A: number, axis?: number): /*elided*/ any;
        dot(b: import("../pathux.js").IBaseVector<2>): number;
        loadX(x: number): /*elided*/ any;
        loadXY(x: number, y: number): /*elided*/ any;
        swapAxes(axis1: 0 | 1, axis2: 0 | 1): /*elided*/ any;
        sinterp(v2: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
        perpSwap(axis1?: 0 | 1, axis2?: 0 | 1, sign?: number): /*elided*/ any;
        normalize(): /*elided*/ any;
        multVecMatrix(matrix: import("../pathux.js").Matrix4, ignore_w?: boolean): /*elided*/ any;
        mulVecQuat(q: import("../pathux.js").IQuat): /*elided*/ any;
        preNormalizedAngle(v2: import("../pathux.js").IBaseVector<2>): number;
        loadSTRUCT(reader: StructReader</*elided*/ any>): void;
    };
    get pos(): {
        [k: number]: number | undefined;
        0: number;
        1: number;
        length: number;
        LEN: 2;
        [Symbol.iterator]: (() => ArrayIterator<any>) | (() => ArrayIterator<number>);
        slice: (start?: number, end?: number) => number[];
        load(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        load2(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        normalizedDot(b: import("../pathux.js").IBaseVector<2>): number;
        equals(b: import("../pathux.js").IBaseVector<2>): boolean;
        zero(): /*elided*/ any;
        negate(): /*elided*/ any;
        combine(b: import("../pathux.js").IBaseVector<2>, u: number, v: number): /*elided*/ any;
        interp(b: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
        add(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        addFac(b: import("../pathux.js").IBaseVector<2>, f: number): /*elided*/ any;
        fract(): /*elided*/ any;
        sub(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        mul(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        div(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        mulScalar(b: number): /*elided*/ any;
        divScalar(b: number): /*elided*/ any;
        addScalar(b: number): /*elided*/ any;
        subScalar(b: number): /*elided*/ any;
        minScalar(b: number): /*elided*/ any;
        maxScalar(b: number): /*elided*/ any;
        ceil(): /*elided*/ any;
        floor(): /*elided*/ any;
        abs(): /*elided*/ any;
        min(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        max(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        clamp(min: number, max: number): /*elided*/ any;
        vectorDotDistance(b: import("../pathux.js").IBaseVector<2>): number;
        vectorDistance(b: import("../pathux.js").IBaseVector<2>): number;
        vectorDistanceSqr(b: import("../pathux.js").IBaseVector<2>): number;
        copy(): /*elided*/ any;
        vectorLengthSqr(): number;
        vectorLength(): number;
        rot2d(A: number, axis?: number): /*elided*/ any;
        dot(b: import("../pathux.js").IBaseVector<2>): number;
        loadX(x: number): /*elided*/ any;
        loadXY(x: number, y: number): /*elided*/ any;
        swapAxes(axis1: 0 | 1, axis2: 0 | 1): /*elided*/ any;
        sinterp(v2: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
        perpSwap(axis1?: 0 | 1, axis2?: 0 | 1, sign?: number): /*elided*/ any;
        normalize(): /*elided*/ any;
        multVecMatrix(matrix: import("../pathux.js").Matrix4, ignore_w?: boolean): /*elided*/ any;
        mulVecQuat(q: import("../pathux.js").IQuat): /*elided*/ any;
        preNormalizedAngle(v2: import("../pathux.js").IBaseVector<2>): number;
        loadSTRUCT(reader: StructReader</*elided*/ any>): void;
    };
    set pos(val: {
        [k: number]: number | undefined;
        0: number;
        1: number;
        length: number;
        LEN: 2;
        [Symbol.iterator]: (() => ArrayIterator<any>) | (() => ArrayIterator<number>);
        slice: (start?: number, end?: number) => number[];
        load(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        load2(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        normalizedDot(b: import("../pathux.js").IBaseVector<2>): number;
        equals(b: import("../pathux.js").IBaseVector<2>): boolean;
        zero(): /*elided*/ any;
        negate(): /*elided*/ any;
        combine(b: import("../pathux.js").IBaseVector<2>, u: number, v: number): /*elided*/ any;
        interp(b: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
        add(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        addFac(b: import("../pathux.js").IBaseVector<2>, f: number): /*elided*/ any;
        fract(): /*elided*/ any;
        sub(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        mul(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        div(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        mulScalar(b: number): /*elided*/ any;
        divScalar(b: number): /*elided*/ any;
        addScalar(b: number): /*elided*/ any;
        subScalar(b: number): /*elided*/ any;
        minScalar(b: number): /*elided*/ any;
        maxScalar(b: number): /*elided*/ any;
        ceil(): /*elided*/ any;
        floor(): /*elided*/ any;
        abs(): /*elided*/ any;
        min(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        max(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        clamp(min: number, max: number): /*elided*/ any;
        vectorDotDistance(b: import("../pathux.js").IBaseVector<2>): number;
        vectorDistance(b: import("../pathux.js").IBaseVector<2>): number;
        vectorDistanceSqr(b: import("../pathux.js").IBaseVector<2>): number;
        copy(): /*elided*/ any;
        vectorLengthSqr(): number;
        vectorLength(): number;
        rot2d(A: number, axis?: number): /*elided*/ any;
        dot(b: import("../pathux.js").IBaseVector<2>): number;
        loadX(x: number): /*elided*/ any;
        loadXY(x: number, y: number): /*elided*/ any;
        swapAxes(axis1: 0 | 1, axis2: 0 | 1): /*elided*/ any;
        sinterp(v2: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
        perpSwap(axis1?: 0 | 1, axis2?: 0 | 1, sign?: number): /*elided*/ any;
        normalize(): /*elided*/ any;
        multVecMatrix(matrix: import("../pathux.js").Matrix4, ignore_w?: boolean): /*elided*/ any;
        mulVecQuat(q: import("../pathux.js").IQuat): /*elided*/ any;
        preNormalizedAngle(v2: import("../pathux.js").IBaseVector<2>): number;
        loadSTRUCT(reader: StructReader</*elided*/ any>): void;
    });
    get size(): {
        [k: number]: number | undefined;
        0: number;
        1: number;
        length: number;
        LEN: 2;
        [Symbol.iterator]: (() => ArrayIterator<any>) | (() => ArrayIterator<number>);
        slice: (start?: number, end?: number) => number[];
        load(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        load2(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        normalizedDot(b: import("../pathux.js").IBaseVector<2>): number;
        equals(b: import("../pathux.js").IBaseVector<2>): boolean;
        zero(): /*elided*/ any;
        negate(): /*elided*/ any;
        combine(b: import("../pathux.js").IBaseVector<2>, u: number, v: number): /*elided*/ any;
        interp(b: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
        add(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        addFac(b: import("../pathux.js").IBaseVector<2>, f: number): /*elided*/ any;
        fract(): /*elided*/ any;
        sub(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        mul(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        div(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        mulScalar(b: number): /*elided*/ any;
        divScalar(b: number): /*elided*/ any;
        addScalar(b: number): /*elided*/ any;
        subScalar(b: number): /*elided*/ any;
        minScalar(b: number): /*elided*/ any;
        maxScalar(b: number): /*elided*/ any;
        ceil(): /*elided*/ any;
        floor(): /*elided*/ any;
        abs(): /*elided*/ any;
        min(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        max(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        clamp(min: number, max: number): /*elided*/ any;
        vectorDotDistance(b: import("../pathux.js").IBaseVector<2>): number;
        vectorDistance(b: import("../pathux.js").IBaseVector<2>): number;
        vectorDistanceSqr(b: import("../pathux.js").IBaseVector<2>): number;
        copy(): /*elided*/ any;
        vectorLengthSqr(): number;
        vectorLength(): number;
        rot2d(A: number, axis?: number): /*elided*/ any;
        dot(b: import("../pathux.js").IBaseVector<2>): number;
        loadX(x: number): /*elided*/ any;
        loadXY(x: number, y: number): /*elided*/ any;
        swapAxes(axis1: 0 | 1, axis2: 0 | 1): /*elided*/ any;
        sinterp(v2: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
        perpSwap(axis1?: 0 | 1, axis2?: 0 | 1, sign?: number): /*elided*/ any;
        normalize(): /*elided*/ any;
        multVecMatrix(matrix: import("../pathux.js").Matrix4, ignore_w?: boolean): /*elided*/ any;
        mulVecQuat(q: import("../pathux.js").IQuat): /*elided*/ any;
        preNormalizedAngle(v2: import("../pathux.js").IBaseVector<2>): number;
        loadSTRUCT(reader: StructReader</*elided*/ any>): void;
    };
    set size(val: {
        [k: number]: number | undefined;
        0: number;
        1: number;
        length: number;
        LEN: 2;
        [Symbol.iterator]: (() => ArrayIterator<any>) | (() => ArrayIterator<number>);
        slice: (start?: number, end?: number) => number[];
        load(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        load2(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        normalizedDot(b: import("../pathux.js").IBaseVector<2>): number;
        equals(b: import("../pathux.js").IBaseVector<2>): boolean;
        zero(): /*elided*/ any;
        negate(): /*elided*/ any;
        combine(b: import("../pathux.js").IBaseVector<2>, u: number, v: number): /*elided*/ any;
        interp(b: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
        add(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        addFac(b: import("../pathux.js").IBaseVector<2>, f: number): /*elided*/ any;
        fract(): /*elided*/ any;
        sub(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        mul(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        div(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        mulScalar(b: number): /*elided*/ any;
        divScalar(b: number): /*elided*/ any;
        addScalar(b: number): /*elided*/ any;
        subScalar(b: number): /*elided*/ any;
        minScalar(b: number): /*elided*/ any;
        maxScalar(b: number): /*elided*/ any;
        ceil(): /*elided*/ any;
        floor(): /*elided*/ any;
        abs(): /*elided*/ any;
        min(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        max(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
        clamp(min: number, max: number): /*elided*/ any;
        vectorDotDistance(b: import("../pathux.js").IBaseVector<2>): number;
        vectorDistance(b: import("../pathux.js").IBaseVector<2>): number;
        vectorDistanceSqr(b: import("../pathux.js").IBaseVector<2>): number;
        copy(): /*elided*/ any;
        vectorLengthSqr(): number;
        vectorLength(): number;
        rot2d(A: number, axis?: number): /*elided*/ any;
        dot(b: import("../pathux.js").IBaseVector<2>): number;
        loadX(x: number): /*elided*/ any;
        loadXY(x: number, y: number): /*elided*/ any;
        swapAxes(axis1: 0 | 1, axis2: 0 | 1): /*elided*/ any;
        sinterp(v2: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
        perpSwap(axis1?: 0 | 1, axis2?: 0 | 1, sign?: number): /*elided*/ any;
        normalize(): /*elided*/ any;
        multVecMatrix(matrix: import("../pathux.js").Matrix4, ignore_w?: boolean): /*elided*/ any;
        mulVecQuat(q: import("../pathux.js").IQuat): /*elided*/ any;
        preNormalizedAngle(v2: import("../pathux.js").IBaseVector<2>): number;
        loadSTRUCT(reader: StructReader</*elided*/ any>): void;
    });
    static newSTRUCT(): HTMLElement;
    static define(): {
        tagname: string;
    };
    _get_v_suffix(): string;
    bringToFront(): void;
    _side(border: ScreenArea<CTX>["_borders"][number]): number;
    init(): void;
    draw(): void;
    _isDead(): true | undefined;
    toJSON(): Record<string, unknown> & {
        editors: Area<CTX>[] & {
            remove(item: Area<CTX>, b?: boolean): void;
        };
        _sarea_id: number;
        area: string;
        pos: {
            [k: number]: number | undefined;
            0: number;
            1: number;
            length: number;
            LEN: 2;
            [Symbol.iterator]: (() => ArrayIterator<any>) | (() => ArrayIterator<number>);
            slice: (start?: number, end?: number) => number[];
            load(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
            load2(existing: number[] | import("../pathux.js").IBaseVector<2>): /*elided*/ any;
            normalizedDot(b: import("../pathux.js").IBaseVector<2>): number;
            equals(b: import("../pathux.js").IBaseVector<2>): boolean;
            zero(): /*elided*/ any;
            negate(): /*elided*/ any;
            combine(b: import("../pathux.js").IBaseVector<2>, u: number, v: number): /*elided*/ any;
            interp(b: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
            add(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
            addFac(b: import("../pathux.js").IBaseVector<2>, f: number): /*elided*/ any;
            fract(): /*elided*/ any;
            sub(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
            mul(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
            div(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
            mulScalar(b: number): /*elided*/ any;
            divScalar(b: number): /*elided*/ any;
            addScalar(b: number): /*elided*/ any;
            subScalar(b: number): /*elided*/ any;
            minScalar(b: number): /*elided*/ any;
            maxScalar(b: number): /*elided*/ any;
            ceil(): /*elided*/ any;
            floor(): /*elided*/ any;
            abs(): /*elided*/ any;
            min(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
            max(b: import("../pathux.js").IBaseVector<2>): /*elided*/ any;
            clamp(min: number, max: number): /*elided*/ any;
            vectorDotDistance(b: import("../pathux.js").IBaseVector<2>): number;
            vectorDistance(b: import("../pathux.js").IBaseVector<2>): number;
            vectorDistanceSqr(b: import("../pathux.js").IBaseVector<2>): number;
            copy(): /*elided*/ any;
            vectorLengthSqr(): number;
            vectorLength(): number;
            rot2d(A: number, axis?: number): /*elided*/ any;
            dot(b: import("../pathux.js").IBaseVector<2>): number;
            loadX(x: number): /*elided*/ any;
            loadXY(x: number, y: number): /*elided*/ any;
            swapAxes(axis1: 0 | 1, axis2: 0 | 1): /*elided*/ any;
            sinterp(v2: import("../pathux.js").IBaseVector<2>, t: number): /*elided*/ any;
            perpSwap(axis1?: 0 | 1, axis2?: 0 | 1, sign?: number): /*elided*/ any;
            normalize(): /*elided*/ any;
            multVecMatrix(matrix: import("../pathux.js").Matrix4, ignore_w?: boolean): /*elided*/ any;
            mulVecQuat(q: import("../pathux.js").IQuat): /*elided*/ any;
            preNormalizedAngle(v2: import("../pathux.js").IBaseVector<2>): number;
            loadSTRUCT(reader: StructReader</*elided*/ any>): void;
        };
        size: {
            [k: number]: number | undefined;
            0: number;
            1: number;
            length: number;
            LEN: 2;
            [Symbol.iterator]: (() => ArrayIterator<any>) | (() => ArrayIterator<number>);
            slice: (start?: number, end?: number) => number[];
            load(existing: number[] | import("../pathux.js").IBaseVector<2>): any;
            load2(existing: number[] | import("../pathux.js").IBaseVector<2>): any;
            normalizedDot(b: import("../pathux.js").IBaseVector<2>): number;
            equals(b: import("../pathux.js").IBaseVector<2>): boolean;
            zero(): any;
            negate(): any;
            combine(b: import("../pathux.js").IBaseVector<2>, u: number, v: number): any;
            interp(b: import("../pathux.js").IBaseVector<2>, t: number): any;
            add(b: import("../pathux.js").IBaseVector<2>): any;
            addFac(b: import("../pathux.js").IBaseVector<2>, f: number): any;
            fract(): any;
            sub(b: import("../pathux.js").IBaseVector<2>): any;
            mul(b: import("../pathux.js").IBaseVector<2>): any;
            div(b: import("../pathux.js").IBaseVector<2>): any;
            mulScalar(b: number): any;
            divScalar(b: number): any;
            addScalar(b: number): any;
            subScalar(b: number): any;
            minScalar(b: number): any;
            maxScalar(b: number): any;
            ceil(): any;
            floor(): any;
            abs(): any;
            min(b: import("../pathux.js").IBaseVector<2>): any;
            max(b: import("../pathux.js").IBaseVector<2>): any;
            clamp(min: number, max: number): any;
            vectorDotDistance(b: import("../pathux.js").IBaseVector<2>): number;
            vectorDistance(b: import("../pathux.js").IBaseVector<2>): number;
            vectorDistanceSqr(b: import("../pathux.js").IBaseVector<2>): number;
            copy(): any;
            vectorLengthSqr(): number;
            vectorLength(): number;
            rot2d(A: number, axis?: number): any;
            dot(b: import("../pathux.js").IBaseVector<2>): number;
            loadX(x: number): any;
            loadXY(x: number, y: number): any;
            swapAxes(axis1: 0 | 1, axis2: 0 | 1): any;
            sinterp(v2: import("../pathux.js").IBaseVector<2>, t: number): any;
            perpSwap(axis1?: 0 | 1, axis2?: 0 | 1, sign?: number): any;
            normalize(): any;
            multVecMatrix(matrix: import("../pathux.js").Matrix4, ignore_w?: boolean): any;
            mulVecQuat(q: import("../pathux.js").IQuat): any;
            preNormalizedAngle(v2: import("../pathux.js").IBaseVector<2>): number;
            loadSTRUCT(reader: StructReader<any>): void;
        };
    };
    on_keydown(e: KeyboardEvent): void;
    loadJSON(obj: Record<string, unknown>): void;
    _ondestroy(): void;
    getScreen(): Screen<CTX> | undefined;
    copy(screen: Screen<CTX>): ScreenArea<CTX>;
    snapToScreenSize(): void;
    /**
     *
     * Sets screen verts from pos/size
     * */
    loadFromPosSize(): this | undefined;
    /**
     *
     * Sets pos/size from screen verts
     * */
    loadFromVerts(): this | undefined;
    on_resize(size: number[] | Vector2): void;
    makeBorders(screen: Screen<CTX>): this;
    setCSS(): void;
    appendChild<T extends Node>(child: T): T;
    switch_editor(cls: AreaConstructorParam): void;
    switchEditor(cls: AreaConstructorParam): void;
    _checkWrangler(): void;
    update(): void;
    removeChild<T extends Node>(ch: T): T;
    afterSTRUCT(): void;
    loadSTRUCT(reader: StructReader<this>): void;
}
export type ScreenAreaAny = ScreenArea<any>;
export type AreaAny = Area<any>;
//# sourceMappingURL=ScreenArea.d.ts.map