export declare function rgb_to_hsv(r: number, g: number, b: number): number[];
export declare function hsv_to_rgb(h: number, s: number, v: number): number[];
export declare function cmyk_to_rgb(c: number, m: number, y: number, k: number): {
    [k: number]: number | undefined;
    0: number;
    1: number;
    2: number;
    length: number;
    LEN: 3;
    [Symbol.iterator]: (() => ArrayIterator<any>) | (() => ArrayIterator<number>);
    slice: (start?: number, end?: number) => number[];
    load(existing: number[] | import("../controller.js").IBaseVector<3>): /*elided*/ any;
    load2(existing: number[] | import("../controller.js").IBaseVector<2>): /*elided*/ any;
    load3(existing: number[] | import("../controller.js").IBaseVector<3>): /*elided*/ any;
    normalizedDot(b: import("../controller.js").IBaseVector<3>): number;
    equals(b: import("../controller.js").IBaseVector<3>): boolean;
    zero(): /*elided*/ any;
    negate(): /*elided*/ any;
    combine(b: import("../controller.js").IBaseVector<3>, u: number, v: number): /*elided*/ any;
    interp(b: import("../controller.js").IBaseVector<3>, t: number): /*elided*/ any;
    add(b: import("../controller.js").IBaseVector<3>): /*elided*/ any;
    addFac(b: import("../controller.js").IBaseVector<3>, f: number): /*elided*/ any;
    fract(): /*elided*/ any;
    sub(b: import("../controller.js").IBaseVector<3>): /*elided*/ any;
    mul(b: import("../controller.js").IBaseVector<3>): /*elided*/ any;
    div(b: import("../controller.js").IBaseVector<3>): /*elided*/ any;
    mulScalar(b: number): /*elided*/ any;
    divScalar(b: number): /*elided*/ any;
    addScalar(b: number): /*elided*/ any;
    subScalar(b: number): /*elided*/ any;
    minScalar(b: number): /*elided*/ any;
    maxScalar(b: number): /*elided*/ any;
    ceil(): /*elided*/ any;
    floor(): /*elided*/ any;
    abs(): /*elided*/ any;
    min(b: import("../controller.js").IBaseVector<3>): /*elided*/ any;
    max(b: import("../controller.js").IBaseVector<3>): /*elided*/ any;
    clamp(min: number, max: number): /*elided*/ any;
    vectorDotDistance(b: import("../controller.js").IBaseVector<3>): number;
    vectorDistance(b: import("../controller.js").IBaseVector<3>): number;
    vectorDistanceSqr(b: import("../controller.js").IBaseVector<3>): number;
    copy(): /*elided*/ any;
    vectorLengthSqr(): number;
    vectorLength(): number;
    rot2d(A: number, axis?: number): /*elided*/ any;
    dot(b: import("../controller.js").IBaseVector<3>): number;
    loadX(x: number): /*elided*/ any;
    loadXY(x: number, y: number): /*elided*/ any;
    loadXYZ(x: number, y: number, z: number): /*elided*/ any;
    swapAxes(axis1: 0 | 1 | 2, axis2: 0 | 1 | 2): /*elided*/ any;
    sinterp(v2: import("../controller.js").IBaseVector<3>, t: number): /*elided*/ any;
    perpSwap(axis1?: 0 | 1 | 2, axis2?: 0 | 1 | 2, sign?: number): /*elided*/ any;
    normalize(): /*elided*/ any;
    multVecMatrix(matrix: import("../controller.js").Matrix4, ignore_w?: boolean): number;
    mulVecQuat(q: import("../controller.js").IQuat): /*elided*/ any;
    cross(v: import("../controller.js").IBaseVector<3>): /*elided*/ any;
    preNormalizedAngle(v2: import("../controller.js").IBaseVector<3>): number;
    toCSS(): string;
    loadSTRUCT(reader: import("nstructjs").StructReader</*elided*/ any>): void;
};
export declare function rgb_to_cmyk(r: number, g: number, b: number): {
    [k: number]: number | undefined;
    0: number;
    1: number;
    2: number;
    3: number;
    length: number;
    LEN: 4;
    [Symbol.iterator]: (() => ArrayIterator<any>) | (() => ArrayIterator<number>);
    slice: (start?: number, end?: number) => number[];
    load(existing: number[] | import("../controller.js").IBaseVector<4>): /*elided*/ any;
    load2(existing: number[] | import("../controller.js").IBaseVector<2>): /*elided*/ any;
    load3(existing: number[] | import("../controller.js").IBaseVector<3>): /*elided*/ any;
    load4(existing: number[] | import("../controller.js").IBaseVector<4>): /*elided*/ any;
    normalizedDot(b: import("../controller.js").IBaseVector<4>): number;
    equals(b: import("../controller.js").IBaseVector<4>): boolean;
    zero(): /*elided*/ any;
    negate(): /*elided*/ any;
    combine(b: import("../controller.js").IBaseVector<4>, u: number, v: number): /*elided*/ any;
    interp(b: import("../controller.js").IBaseVector<4>, t: number): /*elided*/ any;
    add(b: import("../controller.js").IBaseVector<4>): /*elided*/ any;
    addFac(b: import("../controller.js").IBaseVector<4>, f: number): /*elided*/ any;
    fract(): /*elided*/ any;
    sub(b: import("../controller.js").IBaseVector<4>): /*elided*/ any;
    mul(b: import("../controller.js").IBaseVector<4>): /*elided*/ any;
    div(b: import("../controller.js").IBaseVector<4>): /*elided*/ any;
    mulScalar(b: number): /*elided*/ any;
    divScalar(b: number): /*elided*/ any;
    addScalar(b: number): /*elided*/ any;
    subScalar(b: number): /*elided*/ any;
    minScalar(b: number): /*elided*/ any;
    maxScalar(b: number): /*elided*/ any;
    ceil(): /*elided*/ any;
    floor(): /*elided*/ any;
    abs(): /*elided*/ any;
    min(b: import("../controller.js").IBaseVector<4>): /*elided*/ any;
    max(b: import("../controller.js").IBaseVector<4>): /*elided*/ any;
    clamp(min: number, max: number): /*elided*/ any;
    vectorDotDistance(b: import("../controller.js").IBaseVector<4>): number;
    vectorDistance(b: import("../controller.js").IBaseVector<4>): number;
    vectorDistanceSqr(b: import("../controller.js").IBaseVector<4>): number;
    copy(): /*elided*/ any;
    vectorLengthSqr(): number;
    vectorLength(): number;
    rot2d(A: number, axis?: number): /*elided*/ any;
    dot(b: import("../controller.js").IBaseVector<4>): number;
    loadX(x: number): /*elided*/ any;
    loadXY(x: number, y: number): /*elided*/ any;
    loadXYZ(x: number, y: number, z: number): /*elided*/ any;
    loadXYZW(x: number, y: number, z: number, w: number): /*elided*/ any;
    swapAxes(axis1: 0 | 1 | 2 | 3, axis2: 0 | 1 | 2 | 3): /*elided*/ any;
    sinterp(v2: import("../controller.js").IBaseVector<4>, t: number): /*elided*/ any;
    perpSwap(axis1?: 0 | 1 | 2 | 3, axis2?: 0 | 1 | 2 | 3, sign?: number): /*elided*/ any;
    normalize(): /*elided*/ any;
    multVecMatrix(matrix: import("../controller.js").Matrix4): number;
    mulVecQuat(q: import("../controller.js").IQuat): /*elided*/ any;
    cross(v: import("../controller.js").IBaseVector<4>): /*elided*/ any;
    preNormalizedAngle(v2: import("../controller.js").IBaseVector<4>): number;
    toCSS(): string;
    loadSTRUCT(reader: import("nstructjs").StructReader</*elided*/ any>): void;
};
//# sourceMappingURL=colorutils.d.ts.map