export declare const Icons: {
    FOLDER: number;
    FILE: number;
    TINY_X: number;
    SMALL_PLUS: number;
    SMALL_MINUS: number;
    UNDO: number;
    REDO: number;
    HELP: number;
    ENUM_UNCHECKED: number;
    ENUM_CHECKED: number;
    LARGE_CHECK: number;
    CURSOR_ARROW: number;
    NOTE_EXCL: number;
    SCROLL_DOWN: number;
    SCROLL_UP: number;
    BACKSPACE: number;
    LEFT_ARROW: number;
    RIGHT_ARROW: number;
    UI_EXPAND: number;
    UI_COLLAPSE: number;
    BOLD: number;
    ITALIC: number;
    UNDERLINE: number;
    STRIKETHRU: number;
    TREE_EXPAND: number;
    TREE_COLLAPSE: number;
    ZOOM_OUT: number;
    ZOOM_IN: number;
};
export declare function loadDefaultIconSheet(): HTMLImageElement;
//# sourceMappingURL=icons.d.ts.map